create table "public"."checkins" (
    "checkin_id" bigint generated by default as identity not null,
    "user_id" text not null,
    "location_id" text not null
);


create table "public"."users" (
    "user_id" text not null,
    "user_name" text not null default ''::text,
    "is_user_completed" boolean not null
);


CREATE UNIQUE INDEX checkins_checkin_id_key ON public.checkins USING btree (checkin_id);

CREATE UNIQUE INDEX checkins_pkey ON public.checkins USING btree (checkin_id);

CREATE UNIQUE INDEX unique_user_location ON public.checkins USING btree (user_id, location_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (user_id);

CREATE UNIQUE INDEX users_user_id_key ON public.users USING btree (user_id);

alter table "public"."checkins" add constraint "checkins_pkey" PRIMARY KEY using index "checkins_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."checkins" add constraint "checkins_checkin_id_key" UNIQUE using index "checkins_checkin_id_key";

alter table "public"."checkins" add constraint "checkins_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."checkins" validate constraint "checkins_user_id_fkey";

alter table "public"."checkins" add constraint "unique_user_location" UNIQUE using index "unique_user_location";

alter table "public"."users" add constraint "users_user_id_key" UNIQUE using index "users_user_id_key";

alter table "public"."users" add constraint "users_user_name_check" CHECK ((length(user_name) > 0)) not valid;

alter table "public"."users" validate constraint "users_user_name_check";

grant delete on table "public"."checkins" to "anon";

grant insert on table "public"."checkins" to "anon";

grant references on table "public"."checkins" to "anon";

grant select on table "public"."checkins" to "anon";

grant trigger on table "public"."checkins" to "anon";

grant truncate on table "public"."checkins" to "anon";

grant update on table "public"."checkins" to "anon";

grant delete on table "public"."checkins" to "authenticated";

grant insert on table "public"."checkins" to "authenticated";

grant references on table "public"."checkins" to "authenticated";

grant select on table "public"."checkins" to "authenticated";

grant trigger on table "public"."checkins" to "authenticated";

grant truncate on table "public"."checkins" to "authenticated";

grant update on table "public"."checkins" to "authenticated";

grant delete on table "public"."checkins" to "service_role";

grant insert on table "public"."checkins" to "service_role";

grant references on table "public"."checkins" to "service_role";

grant select on table "public"."checkins" to "service_role";

grant trigger on table "public"."checkins" to "service_role";

grant truncate on table "public"."checkins" to "service_role";

grant update on table "public"."checkins" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


