name: "Pull request/Push: Unit test"

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main
jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"
      - name: Install dependencies
        run: go mod download
      - name: Vet
        run: go vet ./...
      - name: Test
        run: |
          go test  -v -coverpkg ./src/... -coverprofile coverage.out -covermode count ./tests/...
          go tool cover -func="./coverage.out"
